version: "3"
services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongodata:/data/db
    command: --smallfiles
    # environment:
      # MONGO_INITDB_DATABASE: fixit
      # MONGO_INITDB_ROOT_USERNAME: axway
      # MONGO_INITDB_ROOT_PASSWORD: Axway2019
    ports:
      - "27017:27017"
    networks:
      - acmenet
  fixit:
    image: vbelfoure/fixit-vendor-app:latest
    depends_on:
      - mongo
    ports:
      - "8010:8010"
    networks:
      - acmenet
  repairit:
    image: vbelfoure/repairit-vendor-app:latest
    depends_on:
      - mongo
    ports:
      - "8011:8011"
    networks:
      - acmenet
  patchit:
    image: vbelfoure/patchit-vendor-app:latest
    depends_on:
      - mongo
    ports:
      - "8012:8012"
    networks:
      - acmenet
volumes:
  mongodata:
networks:
  acmenet:
